#line 2 "pyi/lexer.lex.cc"

#line 4 "pyi/lexer.lex.cc"

#define  YY_INT_ALIGNED long int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE pytyperestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 131072

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE pytypelex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via pytyperestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void pytyperestart (FILE *input_file ,yyscan_t yyscanner );
void pytype_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE pytype_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void pytype_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void pytype_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void pytypepush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void pytypepop_buffer_state (yyscan_t yyscanner );

static void pytypeensure_buffer_stack (yyscan_t yyscanner );
static void pytype_load_buffer_state (yyscan_t yyscanner );
static void pytype_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER pytype_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE pytype_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE pytype_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE pytype_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *pytypealloc (yy_size_t ,yyscan_t yyscanner );
void *pytyperealloc (void *,yy_size_t ,yyscan_t yyscanner );
void pytypefree (void * ,yyscan_t yyscanner );

#define yy_new_buffer pytype_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        pytypeensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pytype_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        pytypeensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pytype_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define pytypewrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int32_t yy_accept[183] =
    {   0,
        0,    0,    0,    0,    0,    0,   42,   42,   47,   47,    0,    0,   62,   60,    1,    2,   60,   12,   52,   12,    6,    7,    3,   60,   60,    3,   38,    3,    3,    3,   36,   36,   36,    4,    5,   60,   36,   36,   36,   36,   36,   36,   36,   36,   36,   36,   36,   36,   36,   58,   55,   57,   59,   42,   43,   44,   47,   48,   49,   53,   54,    2,   16,    0,    0,    0,    0,    0,   38,   13,    0,   39,   40,   17,   15,   18,   36,   36,   36,    0,   36,   29,    0,    0,   36,   36,   36,   36,   23,   36,   36,   24,   36,   36,   36,    0,    0,   55,   57,   56,   42,   44,   47,   49,   53,   46,    0,   41,   14,   39,   36,   36,    0,   37,   25,    9,    8,   36,   20,   36,   36,   36,   36,   36,   36,   36,   36,   11,   10,   45,   50,    0,   36,   36,   36,   22,   21,   28,   36,   36,   26,   36,   36,    0,   36,   36,   19,   36,   36,   30,   36,   51,   36,   36,   27,   36,   36,   36,   34,   31,    0,   36,    0,    0,   36,    0,    0,   32,    0,    0,    0,    0,    0,    0,    0,    0,    0,   35,    0,    0,   33,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    3,    4,    5,    6,    1,    1,    1,    7,    8,    9,   10,   11,   10,   12,   13,    1,   14,   14,   14,   14,   14,   14,   14,   14,   14,   14,   15,    1,   16,   17,   18,   10,   10,   19,   19,   19,   19,   19,   19,   19,   19,   19,   19,   19,   19,   19,   20,   19,   19,   19,   19,   19,   21,   19,   22,   19,   19,   19,   19,   23,    1,   24,    1,   19,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,   19,   19,   35,   36,   37,   38,   39,   19,   40,   41,   42,   43,   19,   19,   19,   44,   19,    1,    1,    1,   45,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[46] =
    {   0,
        1,    2,    1,    1,    3,    1,    4,    1,    1,    1,    1,    5,    1,    5,    1,    1,    1,    1,    6,    6,    6,    6,    1,    1,    7,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    8
    } ;

static yyconst flex_int32_t yy_base[194] =
    {   0,
        0,    0,   44,   46,  256,  255,   48,   49,   52,   56,  254,  253,  254,  259,  259,  250,  235,  246,   49,  243,  259,  259,  259,   46,   49,   51,   55,  232,  231,  230,    0,  220,  201,  259,  259,    0,   29,   66,  209,  213,  207,  201,   41,  202,  199,  212,  211,  192,   69,  259,  259,   76,  259,    0,  259,  228,    0,  259,  229,    0,  259,  230,  259,  227,   50,  187,  223,  215,   67,  259,  215,  213,  212,  259,  259,  259,    0,  189,  185,  198,  193,    0,  216,  213,  193,  187,   49,  179,    0,  177,  173,    0,  173,  179,  173,  206,  203,  259,   82,  259,    0,  202,    0,  203,    0,  259,  168,  259,  259,  192,  175,  174,  178,  259,    0,  259,  259,  161,    0,  170,  170,  163,  160,  164,  155,  154,  160,  259,  259,  259,  259,  163,  163,  169,  149,    0,    0,    0,  149,  154,    0,  157,  149,  170,  163,  157,    0,  140,  144,    0,  148,  259,  136,  138,    0,  145,  163,  136,    0,    0,   66,  139,  147,  128,  141,  134,  130,    0,  138,  137,  137,  133,  127,  121,   98,   99,   97,  259,   54,   45,  259,  259,   92,  100,  108,  116,  124,  128,  129,  137,  145,  153,  157
    } ;

static yyconst flex_int32_t yy_def[194] =
    {   0,
      182,    1,  183,  183,  184,  184,  185,  185,  186,  186,  187,  187,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  188,  188,  188,  182,  182,  189,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  182,  182,  182,  182,  190,  182,  182,  191,  182,  182,  192,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  188,  188,  188,  193,  188,  188,  182,  182,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  182,  182,  182,  182,  182,  190,  182,  191,  182,  192,  182,  182,  182,  182,  182,  188,  188,  193,  182,  188,  182,  182,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  182,  182,  182,  182,  182,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  188,  182,  188,  188,  188,  188,  188,  188,  188,  182,  188,  188,  188,  188,  188,  188,  188,  188,  182,  188,  182,  182,  188,  182,  182,  188,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,    0,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182
    } ;

static yyconst flex_int32_t yy_nxt[305] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,   24,   25,   26,   27,   23,   28,   29,   30,   31,   32,   33,   31,   34,   35,   36,   37,   38,   39,   40,   41,   42,   31,   31,   43,   31,   31,   44,   45,   46,   47,   31,   48,   49,   31,   14,   51,   52,   51,   52,   55,   55,   65,   65,   58,   56,   56,   59,   58,   68,   69,   59,   68,   69,   71,   72,   81,   70,   73,   69,   82,   83,   89,   84,   96,  181,   97,   90,   98,   99,   73,   69,  100,  120,   98,   99,  163,  164,  100,  180,  121,   66,   66,   50,   50,   50,   50,   50,   50,   50,   50,   53,   53,   53,   53,   53,   53,   53,   53,   54,   54,   54,   54,   54,   54,   54,   54,   57,   57,   57,   57,   57,   57,   57,   57,   60,   60,   60,   60,   60,   60,   60,   60,   77,   77,   80,  179,   80,  101,  178,  101,  177,  101,  101,  101,  101,  103,  176,  175,  103,  103,  103,  103,  103,  105,  174,  105,  105,  105,  105,  105,  105,  113,  113,  113,  113,  173,  172,  171,  170,  169,  168,  167,  166,  165,  162,  161,  160,  159,  158,  157,  156,  155,  154,  153,  152,  151,  150,  149,  148,  147,  146,  145,  144,  143,  142,  141,  140,  139,  138,  137,  136,  135,  114,  134,  133,  110,  132,  131,  130,  129,  128,  127,  126,  125,  124,  123,  122,  119,  118,  117,  116,  115,  114,  112,  111,  110,   72,  109,   72,  108,  107,  106,   62,  104,  102,   95,   94,   93,   92,   91,   88,   87,   86,   85,   79,   78,   76,   75,   74,   67,   64,   63,   62,  182,   61,   61,   14,   14,   13,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182
    } ;

static yyconst flex_int32_t yy_chk[305] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    3,    3,    4,    4,    7,    8,   19,   65,    9,    7,    8,    9,   10,   24,   24,   10,   25,   25,   26,   26,   37,   25,   27,   27,   37,   38,   43,   38,   49,  180,   49,   43,   52,   52,   69,   69,   52,   87,   99,   99,  161,  161,   99,  179,   87,   19,   65,  183,  183,  183,  183,  183,  183,  183,  183,  184,  184,  184,  184,  184,  184,  184,  184,  185,  185,  185,  185,  185,  185,  185,  185,  186,  186,  186,  186,  186,  186,  186,  186,  187,  187,  187,  187,  187,  187,  187,  187,  188,  188,  189,  177,  189,  190,  176,  190,  175,  190,  190,  190,  190,  191,  174,  173,  191,  191,  191,  191,  191,  192,  172,  192,  192,  192,  192,  192,  192,  193,  193,  193,  193,  171,  170,  169,  167,  166,  165,  164,  163,  162,  158,  157,  156,  154,  153,  151,  149,  148,  146,  145,  144,  143,  142,  140,  139,  135,  134,  133,  132,  127,  126,  125,  124,  123,  122,  121,  120,  118,  113,  112,  111,  110,  107,  104,  102,   97,   96,   95,   94,   93,   91,   90,   88,   86,   85,   84,   83,   81,   80,   79,   78,   73,   72,   71,   68,   67,   66,   64,   62,   59,   56,   48,   47,   46,   45,   44,   42,   41,   40,   39,   33,   32,   30,   29,   28,   20,   18,   17,   16,   13,   12,   11,    6,    5,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182,  182
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[62] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 
    1, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.lex"
/* Exclusive start states. */

#line 17 "lexer.lex"
#include "lexer.h"
#include "parser.tab.hh"
#include "location.hh"

#define YY_EXTRA_TYPE pytype::Lexer*

#define YY_USER_INIT BEGIN(NEWLINE);

#define YYSTYPE pytype::parser::semantic_type
#define YYLTYPE pytype::location

#define YY_USER_ACTION \
  yylval->obj=NULL; \
  yylloc->begin.line = yylineno; \
  yylloc->begin.column = yycolumn; \
  yylloc->end.line = yylineno; \
  yylloc->end.column = yycolumn + yyleng - 1; \
  yycolumn += yyleng;

#if PY_MAJOR_VERSION >= 3
#  define PyInt_FromString PyLong_FromString
#  define PyString_FromFormat PyUnicode_FromFormat
#  define PyString_FromString PyUnicode_FromString
#  define PyString_FromStringAndSize PyUnicode_FromStringAndSize
#endif

typedef pytype::parser::token t;
#line 472 "pyi/lexer.lex.cc"

#define INITIAL 0
#define NEWLINE 1
#define PENDING 2
#define TRIPLE1 3
#define TRIPLE2 4
#define COMMENT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int pytypelex_init (yyscan_t* scanner);

int pytypelex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int pytypelex_destroy (yyscan_t yyscanner );

int pytypeget_debug (yyscan_t yyscanner );

void pytypeset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE pytypeget_extra (yyscan_t yyscanner );

void pytypeset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *pytypeget_in (yyscan_t yyscanner );

void pytypeset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *pytypeget_out (yyscan_t yyscanner );

void pytypeset_out  (FILE * out_str ,yyscan_t yyscanner );

int pytypeget_leng (yyscan_t yyscanner );

char *pytypeget_text (yyscan_t yyscanner );

int pytypeget_lineno (yyscan_t yyscanner );

void pytypeset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * pytypeget_lval (yyscan_t yyscanner );

void pytypeset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *pytypeget_lloc (yyscan_t yyscanner );
    
        void pytypeset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int pytypewrap (yyscan_t yyscanner );
#else
extern int pytypewrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#define YY_READ_BUF_SIZE 131072

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int pytypelex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int pytypelex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp = NULL, *yy_bp = NULL;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 46 "lexer.lex"


#line 719 "pyi/lexer.lex.cc"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			pytypeensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				pytype_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		pytype_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 183 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 182 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 48 "lexer.lex"
{ BEGIN(NEWLINE); yycolumn=1; }  /* Determine indentation. */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "lexer.lex"
{ }  /* Ignore whitespace */
	YY_BREAK
/* Punctuation */
case 3:
YY_RULE_SETUP
#line 52 "lexer.lex"
{ return yytext[0]; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "lexer.lex"
{ ++yyextra->bracket_count_; return yytext[0]; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "lexer.lex"
{ --yyextra->bracket_count_; return yytext[0]; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "lexer.lex"
{ ++yyextra->bracket_count_; return yytext[0]; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "lexer.lex"
{ --yyextra->bracket_count_; return yytext[0]; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "lexer.lex"
{ return t::BYTESTRING; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "lexer.lex"
{ return t::BYTESTRING; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "lexer.lex"
{ return t::UNICODESTRING; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "lexer.lex"
{ return t::UNICODESTRING; }
	YY_BREAK
/* Ignore all other quotes, to simplify processing of forward references. */
case 12:
YY_RULE_SETUP
#line 64 "lexer.lex"
{ }
	YY_BREAK
/* Multi-character punctuation. */
case 13:
YY_RULE_SETUP
#line 67 "lexer.lex"
{ return t::ARROW; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "lexer.lex"
{ return t::ELLIPSIS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "lexer.lex"
{ return t::EQ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 "lexer.lex"
{ return t::NE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 "lexer.lex"
{ return t::LE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "lexer.lex"
{ return t::GE; }
	YY_BREAK
/* Reserved words (must also be added to parse_ext.cc and match
  * parser_constant.py).
  */
case 19:
YY_RULE_SETUP
#line 78 "lexer.lex"
{ return t::CLASS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 "lexer.lex"
{ return t::DEF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 80 "lexer.lex"
{ return t::ELSE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 81 "lexer.lex"
{ return t::ELIF; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 82 "lexer.lex"
{ return t::IF; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 "lexer.lex"
{ return t::OR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 84 "lexer.lex"
{ return t::AND; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 85 "lexer.lex"
{ return t::PASS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "lexer.lex"
{ return t::IMPORT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 "lexer.lex"
{ return t::FROM; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 "lexer.lex"
{ return t::AS; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 "lexer.lex"
{ return t::RAISE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 "lexer.lex"
{ return t::NOTHING; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 "lexer.lex"
{ return t::NAMEDTUPLE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 "lexer.lex"
{ return t::NAMEDTUPLE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 93 "lexer.lex"
{ return t::TYPEVAR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "lexer.lex"
{ return t::TYPEVAR; }
	YY_BREAK
/* NAME */
case 36:
YY_RULE_SETUP
#line 97 "lexer.lex"
{
  yylval->obj=PyString_FromString(yytext);
  return t::NAME;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "lexer.lex"
{
  yylval->obj=PyString_FromStringAndSize(yytext+1, yyleng-2);
  return t::NAME;
}
	YY_BREAK
/* NUMBER */
case 38:
YY_RULE_SETUP
#line 107 "lexer.lex"
{
  yylval->obj=PyInt_FromString(yytext, NULL, 10);
  return t::NUMBER;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 111 "lexer.lex"
{
  yylval->obj=PyFloat_FromDouble(atof(yytext));
  return t::NUMBER;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "lexer.lex"
{
  yylval->obj=PyFloat_FromDouble(atof(yytext));
  return t::NUMBER;
}
	YY_BREAK
/* TRIPLEQUOTED */
case 41:
YY_RULE_SETUP
#line 121 "lexer.lex"
{
  BEGIN(TRIPLE1);
  yyextra->start_line_ = yylineno;
  yyextra->start_column_ = yycolumn - yyleng;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 126 "lexer.lex"
{ }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 127 "lexer.lex"
{ yycolumn = 1; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 128 "lexer.lex"
{ }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 129 "lexer.lex"
{
  BEGIN(INITIAL);
  yylloc->begin.line = yyextra->start_line_;
  yylloc->begin.column = yyextra->start_column_;
  return t::TRIPLEQUOTED;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 136 "lexer.lex"
{
  BEGIN(TRIPLE2);
  yyextra->start_line_ = yylineno;
  yyextra->start_column_ = yycolumn - yyleng;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 141 "lexer.lex"
{ }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 142 "lexer.lex"
{ yycolumn = 1; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 143 "lexer.lex"
{ }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 144 "lexer.lex"
{
  BEGIN(INITIAL);
  yylloc->begin.line = yyextra->start_line_;
  yylloc->begin.column = yyextra->start_column_;
  return t::TRIPLEQUOTED;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 151 "lexer.lex"
{ return t::TYPECOMMENT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 152 "lexer.lex"
{ BEGIN(COMMENT); }
	YY_BREAK
/* Due to a quirk of the flex state machine, matching an empty string
  * does not trigger an action, thus <COMMENT>[^\n]* would not by itself
  * trigger a switch to the INITIAL state if the comment were empty.  In
  * order to deal with this, we have two rules for the COMMENT state: the
  * first consumes any non-empty comment and switchtes to INITIAL.  The second
  * consumes a lone newline and moves to the NEWLINE state.
  */
case 53:
YY_RULE_SETUP
#line 160 "lexer.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 161 "lexer.lex"
{ BEGIN(NEWLINE); yycolumn=1; }
	YY_BREAK
/* NEWLINE state is responsible for processing the whitespace at the start
  * of a line.  It can generate INDENT tokens, queue DEDENT tokens, and
  * eventually exits to either INITIAL or PENDING
  */
/* Ignore empty lines. */
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 170 "lexer.lex"
{ yycolumn = 1; }
	YY_BREAK
/* Ignore comment indentation. */
case 56:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 173 "lexer.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
/* White space at start of line. */
case 57:
YY_RULE_SETUP
#line 176 "lexer.lex"
{
  if (yyextra->bracket_count_) {
    // Ignore indentation within brackets.
    BEGIN(INITIAL);
  } else if (yyleng < yyextra->CurrentIndentation()) {
    // Dedent.
    if (!yyextra->PopIndentationTo(yyleng)) {
      yylval->obj=PyString_FromString("Invalid indentation");
      yyextra->error_message_ = yylval->obj;
      return t::LEXERROR;
    }
    BEGIN(PENDING);
  } else if (yyleng == yyextra->CurrentIndentation()) {
    // No change.
    BEGIN(INITIAL);
  } else {
    // Indent
    yyextra->PushIndentation(yyleng);
    BEGIN(INITIAL);
    return t::INDENT;
  }
}
	YY_BREAK
/* Anything else - put it back and transition to PENDING or INITIAL. */
case 58:
YY_RULE_SETUP
#line 200 "lexer.lex"
{
  yyless(0); yycolumn--;
  if (yyextra->CurrentIndentation()) {
    yyextra->PopIndentationTo(0);
    BEGIN(PENDING);
  } else {
    BEGIN(INITIAL);
  }
}
	YY_BREAK
/* Remain in the PENDING state not consuming anything until all queued
  * DEDENTS have been returned, then transition to INITIAL.
  */
case 59:
YY_RULE_SETUP
#line 213 "lexer.lex"
{
  yyless(0);
  if (yyextra->PopDedent()) {
    return t::DEDENT;
  } else {
    BEGIN(INITIAL);
  }
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NEWLINE):
case YY_STATE_EOF(PENDING):
case YY_STATE_EOF(TRIPLE1):
case YY_STATE_EOF(TRIPLE2):
case YY_STATE_EOF(COMMENT):
#line 222 "lexer.lex"
{
  if (yyextra->CurrentIndentation()) {
    yyextra->PopIndentationTo(0);
  }
  // Ensure a yylval of NULL, even when returning EOF.
  yylval->obj=NULL;
  if (yyextra->PopDedent()) {
    return t::DEDENT;
  } else {
    yyterminate();
  }
}
	YY_BREAK
/* Anything we don't understand is an error. */
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 236 "lexer.lex"
{
  yylval->obj=PyString_FromFormat("Illegal character '%c'", yytext[0]);
  yyextra->error_message_ = yylval->obj;
  return t::LEXERROR;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 242 "lexer.lex"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1249 "pyi/lexer.lex.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * pytypelex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( pytypewrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of pytypelex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					pytyperealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			pytyperestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) pytyperealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 183 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 183 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 182);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					pytyperestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( pytypewrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void pytyperestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        pytypeensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            pytype_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	pytype_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	pytype_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void pytype_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		pytypepop_buffer_state();
	 *		pytypepush_buffer_state(new_buffer);
     */
	pytypeensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	pytype_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (pytypewrap()) processing, but the only time this flag
	 * is looked at is after pytypewrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void pytype_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE pytype_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) pytypealloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pytype_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) pytypealloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in pytype_create_buffer()" );

	b->yy_is_our_buffer = 1;

	pytype_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with pytype_create_buffer()
 * @param yyscanner The scanner object.
 */
    void pytype_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		pytypefree((void *) b->yy_ch_buf ,yyscanner );

	pytypefree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a pytyperestart() or at EOF.
 */
    static void pytype_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	pytype_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then pytype_init_buffer was _probably_
     * called from pytyperestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void pytype_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		pytype_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void pytypepush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	pytypeensure_buffer_stack(yyscanner);

	/* This block is copied from pytype_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from pytype_switch_to_buffer. */
	pytype_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void pytypepop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	pytype_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		pytype_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void pytypeensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)pytypealloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in pytypeensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)pytyperealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in pytypeensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pytype_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) pytypealloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pytype_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	pytype_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to pytypelex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       pytype_scan_bytes() instead.
 */
YY_BUFFER_STATE pytype_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return pytype_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to pytypelex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pytype_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) pytypealloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in pytype_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = pytype_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in pytype_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE pytypeget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int pytypeget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int pytypeget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *pytypeget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *pytypeget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int pytypeget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *pytypeget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void pytypeset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void pytypeset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "pytypeset_lineno called with no buffer" , yyscanner);
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void pytypeset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "pytypeset_column called with no buffer" , yyscanner);
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see pytype_switch_to_buffer
 */
void pytypeset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void pytypeset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int pytypeget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void pytypeset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * pytypeget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void pytypeset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *pytypeget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void pytypeset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* pytypelex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int pytypelex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) pytypealloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* pytypelex_init_extra has the same functionality as pytypelex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to pytypealloc in
 * the yyextra field.
 */

int pytypelex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    pytypeset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) pytypealloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    pytypeset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from pytypelex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * pytypelex_init()
     */
    return 0;
}

/* pytypelex_destroy is for both reentrant and non-reentrant scanners. */
int pytypelex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		pytype_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		pytypepop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	pytypefree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        pytypefree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * pytypelex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    pytypefree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *pytypealloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *pytyperealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void pytypefree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see pytyperealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 242 "lexer.lex"



namespace pytype {

Lexer::Lexer(const char* data, int len)
    : bracket_count_(0), pending_dedents_(0) {
  pytypelex_init(&scanner_);
  pytypeset_extra(this,scanner_);
  pytype_scan_bytes(data,len,scanner_);
  // When using scan_bytes() a new buffer is installed without intializing
  // yylineno, thus it must be explicitly initialized.
  pytypeset_lineno(1,scanner_);
  pytypeset_column(1,scanner_);

  indents_.push_back(0);
}

Lexer::~Lexer() {
  pytypelex_destroy(scanner_);
}

void Lexer::PushIndentation(int width) {
  indents_.push_back(width);
}

bool Lexer::PopIndentationTo(int width) {
  if (width < 0) {
    width = 0;
  }
  pending_dedents_ = 0;
  while (indents_.back() > width) {
    indents_.pop_back();
    pending_dedents_++;
  }
  return indents_.back() == width;
}

bool Lexer::PopDedent() {
  if (pending_dedents_) {
    pending_dedents_--;
    return true;
  } else {
    return false;
  }
}

}  // end namespace pytype

