- id: pytype
  name: Pytype
  description: A static type analyzer for Python code.
  entry: pytype
  # needs to run in the same virtual environment as the code being checked, therefore
  # language = system instead of python
  language: system
  types: [python]
  args:
    - '--jobs=auto'
    - '--keep-going'
  files: \.py$
