#!/usr/bin/python2.7
"""Tool for processing pytd files.

pytd is a type declaration language for Python. Each .py file can have an
accompanying .pytd file that specifies classes, argument types, return types
and exceptions.
This binary processes pytd files, typically to optimize them.

Usage:
  pytd_tool [flags] <inputfile> <outputfile>
"""

import optparse
import sys


from pytype.pytd import optimize
from pytype.pytd import pytd
from pytype.pytd import utils
from pytype.pytd.parse import builtins
from pytype.pytd.parse import parser


def parse_options(args):
  """Use optparse to parse command line options."""
  o = optparse.OptionParser("Usage: %prog [options] infile.pytd outfile.pytd")
  o.add_option(
      "-O", "--optimize", action="store_true",
      dest="optimize", default=False,
      help="Optimize pytd file.")
  o.add_option(
      "--lossy", action="store_true",
      dest="lossy", default=False,
      help="Allow lossy optimizations, such as merging classes.")
  o.add_option(
      "--max-union", type="int", action="store",
      dest="max_union", default=4,
      help="Maximum number of objects in an 'or' clause.\nUse with --lossy.")
  o.add_option(
      "--use-abcs", action="store_true",
      dest="use_abcs", default=False,
      help="Inject abstract bases classes for type merging.\nUse with --lossy.")
  o.add_option(
      "--remove-mutable", action="store_true",
      dest="remove_mutable", default=False,
      help="Remove mutable parameters.")
  o.add_option(
      "-F", "--output-format", type="string", action="store",
      dest="output_format", default="pytd",
      help="Specify output format. Formats: " + ", ".join(utils.OUTPUT_FORMATS))
  options, filenames = o.parse_args(args)
  return options, filenames


def main():
  options, filenames = parse_options(sys.argv)
  unused_executable = filenames.pop(0)
  if len(filenames) == 1:
    filename_in, filename_out = filenames[0], None
  elif len(filenames) == 2:
    filename_in, filename_out = filenames
  else:
    print >>sys.stderr, "Need one or two filenames"
    sys.exit(1)

  if options.output_format not in utils.OUTPUT_FORMATS:
    print >>sys.stderr, "Invalid output format:", options.output_format
    print >>sys.stderr, "Supported formats:", ", ".join(utils.OUTPUT_FORMATS)
    sys.exit(1)

  with open(filename_in) as fi:
    sourcecode = fi.read()
    try:
      parsed = parser.parse_string(sourcecode, filename=filename_in)
    except parser.ParseError as e:
      sys.stderr.write(str(e))
      sys.exit(1)

  if options.optimize:
    parsed = optimize.Optimize(parsed,
                               builtins.GetBuiltinsPyTD(),
                               lossy=options.lossy,
                               use_abcs=options.use_abcs,
                               max_union=options.max_union,
                               remove_mutable=options.remove_mutable,
                               can_do_lookup=False)

  if filename_out is not None:
    out_text = pytd.Print(parsed, print_format=options.output_format)
    if filename_out == "-":
      sys.stdout.write(out_text)
    else:
      with open(filename_out, "w") as out:
        out.write(out_text)


if __name__ == "__main__":
  main()
